server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
          filters:
            - RewritePath=/wallet/(?<path>.*), /$\{path}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        