server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
          - Path=/api/rahaman/service2/**
          filters:
          - RewritePath=/api/rahaman/service2/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
          - Path=/api/rahaman/service1/**
          filters:
          - RewritePath=/api/rahaman/service1/(?<path>.*), /$\{path}
          - SetResponseHeader= assignment9, rahaman
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        